config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      registrations: 'users/registrations'
    }
  
  root "items#index"
  get 'items/new', to: 'items#new' 
  post 'items/new', to: 'items#create'
  resources :users
  resources :items do
    resources :orders, only: [:index, :create]
    collection do
      get 'search'
    end
    resources :likes, only: [:create, :destroy]
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    like = current_user.likes.build(item_id: params[:item_id])
    like.save
    respond_to do |format|
      format.js
    end
  end

  def destroy
    like = Like.find_by(item_id: params[:item_id], user_id: current_user.id)
    like.destroy
    respond_to do |format|
      format.js
    end
  end

end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<% if user_signed_in? && @item.liked_by?(current_user)%>
  <%=link_to "いいね済", item_like_path(@item.id),  data: { turbo_method: :delete }, class: "item_likes",  remote: true %>
<% else %>
  <%=link_to "いいねする", item_likes_path(@item.id), data: { turbo_method: :post }, class: "item_likes", remote: true %>
<% end %>

app/views/likes/create.js.erb
document.getElementById('like-btn<%= @item.id %>').innerHTML = "<%= j(render partial: 'likes/like', locals: {item: @item}) %>"

app/views/likes/destroy.js.erb
document.getElementById('like-btn<%= @item.id %>').innerHTML = "<%= j(render partial: 'likes/like', locals: {item: @item}) %>"